[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"
default-run = "advent-of-code-2023"

[dependencies]
aoc-client = "0.2.0"
clap = { version = "4.4.10", features = ["derive"] }
chrono = "0.4.31"
